language: java
jdk: openjdk11
sudo: required
dist: trusty

services:
  - docker

install: true

before_script:
  - sudo apt-get install jq

jobs:
  include:
    - stage: commit stage
      script:
        # Build execution (unit & integration tests, application packaging, ...)
        - make build
        # Code quality update
        - curl -Ls -o codacy-coverage-reporter "$(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | contains("codacy-coverage-reporter-linux"))) | .[0].browser_download_url')"
        - chmod +x codacy-coverage-reporter
        - ./codacy-coverage-reporter report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
        # Docker registry release
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker tag menu-generation:latest $DOCKER_USERNAME/menu-generation:$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_USERNAME/menu-generation:$TRAVIS_BUILD_NUMBER
    - stage: acceptance testing
      script:
        - docker pull $DOCKER_USERNAME/menu-generation:$TRAVIS_BUILD_NUMBER
        - docker tag $DOCKER_USERNAME/menu-generation:$TRAVIS_BUILD_NUMBER menu-generation:latest
        - make acceptance
    - stage: promote image
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker pull $DOCKER_USERNAME/menu-generation:$TRAVIS_BUILD_NUMBER
        - docker tag $DOCKER_USERNAME/menu-generation:$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/menu-generation:latest
        - docker push $DOCKER_USERNAME/menu-generation:latest

notifications:
  email:
    on_success: change
    on_failure: always
