language: java
jdk: openjdk11
sudo: required
dist: trusty

install: true

jobs:
  include:
    - stage: commit stage
      script:
        - make build

notifications:
  email:
    on_success: change
    on_failure: always
