language: java
jdk: openjdk11
sudo: required
dist: trusty

services:
  - docker

install: true

jobs:
  include:
    - stage: commit stage
      script:
        - make build
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker tag menu-generation:latest $DOCKER_USERNAME/menu-generation:$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_USERNAME/menu-generation:$TRAVIS_BUILD_NUMBER
    - stage: acceptance testing
      script:
        - docker pull $DOCKER_USERNAME/menu-generation:$TRAVIS_BUILD_NUMBER
        - docker tag $DOCKER_USERNAME/menu-generation:$TRAVIS_BUILD_NUMBER menu-generation:latest
        - make acceptance
    - stage: promote image
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker pull $DOCKER_USERNAME/menu-generation:$TRAVIS_BUILD_NUMBER
        - docker tag $DOCKER_USERNAME/menu-generation:$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/menu-generation:latest
        - docker push $DOCKER_USERNAME/menu-generation:latest

notifications:
  email:
    on_success: change
    on_failure: always
