version: '3'
services:
  menu-generation:
    container_name: menu-generation
    image: menu-generation:latest
    ports:
      - 8080:8080
    healthcheck:
      test: curl -f http://localhost:8080/actuator/health || exit 1
      interval: 10s
      timeout: 1s
      retries: 3
