server:
  port: ${API_PORT:8080}
  error:
    include-stacktrace: never

spring:
  profiles:
    active:
      - in-memory

management:
  endpoints:
    web:
      base-path: /api/management
  endpoint:
    health:
      show-details: when_authorized
      roles: ACTUATOR

### Logging configuration
logging:
  level:
    org.adhuc.cena.menu: TRACE
    org.springframework:
      web: ERROR
      security: ERROR
      boot.autoconfigure: ERROR
